### ISSUE TITLE
Should this be moved to serilog org?

### ISSUE THREAD

**Issue by txchen** [nblumhardt/serilog-sinks-json#2]
Thanks for creating this package, I think this is quite useful since I can now write json to file and use external program to read the json and write to log store.
I think writing json to console or file should be supported by serilog officially.

**Comment by nblumhardt** [comment]
Thanks @txchen - yes, that's happening currently, but via another mechanism. I'll reply on your issue report under the Serilog.Sinks.File repo. Cheers!

**Comment by txchen** [comment]
Thanks! @nblumhardt
